"""Semantic-cache test pairs (AWS runs, core bench/RESULTS-aws-2026-10*.md).

Hand-written and adversarial: 36 paraphrase pairs that should hit and 38 near-miss pairs that
must not (different numbers, entities, direction, polarity, scope or intent).
"""

# (a, b): b should be answered by a's cached answer.
PARAPHRASES = [
    ("What is the capital of Australia?", "Which city is Australia's capital?"),
    ("How do I reset my password?", "What are the steps to reset my password?"),
    ("Explain what a mutex is.", "Can you explain what a mutex is?"),
    ("What are the opening hours of the support desk?", "When is the support desk open?"),
    ("How do I export a report to PDF?", "How can I export a report as a PDF?"),
    ("Summarise the benefits of unit testing.", "Give me a summary of the benefits of unit testing."),
    ("What does HTTP status 404 mean?", "What is the meaning of the HTTP 404 status code?"),
    ("How do I convert a string to an integer in Python?", "In Python, how can I turn a string into an int?"),
    ("What is the difference between TCP and UDP?", "How does TCP differ from UDP?"),
    ("How many vacation days do new employees get?", "How much annual leave do new hires receive?"),
    ("Write a SQL query to count rows in the orders table.", "Give me a SQL query that counts the rows of the orders table."),
    ("What is the refund policy for damaged items?", "What's your refund policy if an item arrives damaged?"),
    ("How do I add a new user to the admin console?", "What's the way to add a new user in the admin console?"),
    ("Translate 'good morning' into Spanish.", "How do you say 'good morning' in Spanish?"),
    ("What is Kubernetes used for?", "What do people use Kubernetes for?"),
    ("Explain the CAP theorem briefly.", "Briefly explain the CAP theorem."),
    ("How do I change the billing address on my account?", "How can I update my account's billing address?"),
    ("What are the symptoms of dehydration?", "What symptoms does dehydration cause?"),
    ("How do I undo the last git commit?", "How can I revert my most recent git commit?"),
    ("What is the VAT rate in Germany?", "What's Germany's VAT rate?"),
    ("Who approves expense reports over 5000 EUR?", "Who has to approve expense reports above 5000 EUR?"),
    ("How long does shipping to France take?", "What is the delivery time for shipping to France?"),
    ("What is a foreign key in a database?", "Explain what a database foreign key is."),
    ("Can I work remotely from another country?", "Am I allowed to work remotely from abroad?"),
    ("How do I enable two-factor authentication?", "How can I turn on 2FA?"),
    ("List the main features of the Pro plan.", "What are the key features included in the Pro plan?"),
    ("What is the boiling point of water at sea level?", "At sea level, at what temperature does water boil?"),
    ("How do I cancel my subscription?", "What do I need to do to cancel my subscription?"),
    ("Describe the onboarding process for new engineers.", "What does onboarding look like for a new engineer?"),
    ("What does the error 'connection refused' mean?", "What is meant by a 'connection refused' error?"),
    ("Recommend a good book about distributed systems.", "Can you suggest a good book on distributed systems?"),
    ("How do I format a date as YYYY-MM-DD in JavaScript?", "In JavaScript, how can I format a date as YYYY-MM-DD?"),
    ("What is the maximum file size for uploads?", "How large can uploaded files be at most?"),
    ("When is the next public holiday in Lebanon?", "What's the next public holiday in Lebanon?"),
    ("hi, how do i reset my pasword", "How do I reset my password?"),
    ("What's the weather like in Paris today?", "How is the weather in Paris today?"),
]
# (a, b): b must NOT be answered with a's answer (different numbers, entities, intent or polarity).
NEAR_MISSES = [
    ("What is the capital of Australia?", "What is the capital of Austria?"),
    ("How do I reset my password?", "How do I reset my username?"),
    ("What does HTTP status 404 mean?", "What does HTTP status 403 mean?"),
    ("How many vacation days do new employees get?", "How many sick days do new employees get?"),
    ("Who approves expense reports over 5000 EUR?", "Who approves expense reports over 500 EUR?"),
    ("How long does shipping to France take?", "How long does shipping to Finland take?"),
    ("What is the VAT rate in Germany?", "What is the VAT rate in Greece?"),
    ("How do I convert a string to an integer in Python?", "How do I convert an integer to a string in Python?"),
    ("How do I enable two-factor authentication?", "How do I disable two-factor authentication?"),
    ("How do I cancel my subscription?", "How do I renew my subscription?"),
    ("What is the difference between TCP and UDP?", "What is the difference between TCP and QUIC?"),
    ("Translate 'good morning' into Spanish.", "Translate 'good morning' into Italian."),
    ("Write a SQL query to count rows in the orders table.", "Write a SQL query to delete rows in the orders table."),
    ("What is the refund policy for damaged items?", "What is the refund policy for digital items?"),
    ("How do I undo the last git commit?", "How do I undo the last git push?"),
    ("List the main features of the Pro plan.", "List the main features of the Free plan."),
    ("What is the boiling point of water at sea level?", "What is the boiling point of water on Mount Everest?"),
    ("When is the next public holiday in Lebanon?", "When is the next public holiday in Lithuania?"),
    ("Can I work remotely from another country?", "Can I work remotely from another city?"),
    ("What is the maximum file size for uploads?", "What is the minimum file size for uploads?"),
    ("Show me sales for Q3 2025.", "Show me sales for Q3 2024."),
    ("Show me sales for Q3 2025.", "Show me returns for Q3 2025."),
    ("What was revenue in March?", "What was revenue in May?"),
    ("Book a meeting room for 4 people on Tuesday.", "Book a meeting room for 14 people on Tuesday."),
    ("Book a meeting room for 4 people on Tuesday.", "Cancel the meeting room for 4 people on Tuesday."),
    ("Convert 100 USD to EUR.", "Convert 100 EUR to USD."),
    ("Convert 100 USD to EUR.", "Convert 1000 USD to EUR."),
    ("Is ibuprofen safe during pregnancy?", "Is paracetamol safe during pregnancy?"),
    ("What is the dosage of amoxicillin for adults?", "What is the dosage of amoxicillin for children?"),
    ("How do I add a new user to the admin console?", "How do I remove a user from the admin console?"),
    ("Summarise the benefits of unit testing.", "Summarise the drawbacks of unit testing."),
    ("What are the symptoms of dehydration?", "What are the causes of dehydration?"),
    ("What is the status of order 12345?", "What is the status of order 12346?"),
    ("What is Acme Corp's outstanding balance?", "What is Globex Corp's outstanding balance?"),
    ("Explain the CAP theorem briefly.", "Explain the CAP theorem in detail."),
    ("What is the weather in Paris today?", "What is the weather in Paris tomorrow?"),
    ("Send the invoice to the finance team.", "Send the contract to the finance team."),
    ("How many employees are in the Berlin office?", "How many employees are in the Munich office?"),
]
