-- 0002: wire the control plane to Postgres (crates/caliban-cp/src/store/postgres.rs).
--
-- Applied at startup by the control plane's embedded runner (table caliban_schema_migrations,
-- checksummed, serialized with an advisory lock). Never edit an applied migration; add a new one.
--
-- Access model: the control plane renders cross-tenant snapshots, so it connects as the schema
-- owner (or a BYPASSRLS role). Row-level security from 0001 applies to tenant-scoped roles, which
-- must `SET app.tenant_id = '...'` per transaction.

-- Store metadata (e.g. the one-time seed marker: the config file seeds an empty database once).
CREATE TABLE cp_meta (
    key          TEXT PRIMARY KEY,
    value        TEXT NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Stable listing order (insertion order), independent of timestamps.
ALTER TABLE tenant              ADD COLUMN ord BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE api_key             ADD COLUMN ord BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE provider_credential ADD COLUMN ord BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE model               ADD COLUMN ord BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE datasource          ADD COLUMN ord BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE node                ADD COLUMN ord BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE ontology_element    ADD COLUMN ord BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Extra per-tenant config passed through to the data-plane snapshot (e.g. quotas).
ALTER TABLE tenant ADD COLUMN settings JSONB NOT NULL DEFAULT '{}';

-- BYOK credentials: sealed_key holds the AES-256-GCM blob (nonce ‖ ciphertext) under CALIBAN_KEK
-- (per-tenant DEKs in tenant_dek: TODO). secret_ref holds a *reference* seeded from the config
-- file ({"env": "NAME"} or {"file": "/path"}), never a secret value.
ALTER TABLE provider_credential
    ADD COLUMN cache_salt BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN secret_ref JSONB,
    ADD CONSTRAINT provider_credential_one_secret CHECK (sealed_key IS NULL OR secret_ref IS NULL);

-- Deployment-wide model servers (e.g. an on-prem vLLM pool), optionally restricted to tenants.
CREATE TABLE shared_provider (
    id           TEXT PRIMARY KEY,
    kind         TEXT NOT NULL,
    base_url     TEXT NOT NULL,
    trust_tier   TEXT NOT NULL CHECK (trust_tier IN ('t0_sovereign', 't1_attested', 't2_contracted', 't3_public')),
    cache_salt   BOOLEAN NOT NULL DEFAULT false,
    sealed_key   BYTEA,
    secret_ref   JSONB,
    tenants      TEXT[] NOT NULL DEFAULT '{}',   -- allow-list; empty = every tenant
    ord          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (sealed_key IS NULL OR secret_ref IS NULL)
);

-- Model catalogue: fields the router needs (see caliban-config ModelEntry).
ALTER TABLE model
    ADD COLUMN kind          TEXT NOT NULL DEFAULT 'chat' CHECK (kind IN ('chat', 'embedding', 'rerank')),
    ADD COLUMN family        TEXT,
    ADD COLUMN capabilities  JSONB NOT NULL DEFAULT '{}',
    ADD CONSTRAINT model_trust_tier CHECK (trust_tier IN ('t0_sovereign', 't1_attested', 't2_contracted', 't3_public'));

-- Tenant routes keep their order (first route listed first; first model preferred).
ALTER TABLE route ADD COLUMN position INTEGER NOT NULL DEFAULT 0;

-- Audit log: the store assigns seq itself (it hashes it), under an advisory lock.
ALTER TABLE audit_log ALTER COLUMN seq DROP DEFAULT;
ALTER TABLE audit_log ADD CONSTRAINT audit_log_hash_len CHECK (octet_length(hash) = 32);
CREATE INDEX audit_log_tenant ON audit_log (tenant_id, seq DESC);

-- Append-only: rows can be inserted, never changed or removed.
CREATE FUNCTION audit_log_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only';
END $$;
CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();
