-- 0009: single sign-on (OIDC) and role-based access for the control plane.
-- See crates/caliban-cp/src/auth/.
--
-- Never edit an applied migration; add a new one.
--
-- Users are created just in time on their first login (or first access token) and are keyed by
-- the identity provider's (issuer, subject). Role bindings grant a role to a user or to an IdP
-- group, deployment-wide or for one tenant. Sessions are server-side: the browser holds a random
-- token in an HttpOnly cookie and only its SHA-256 is stored here. Pending logins hold the state,
-- nonce and PKCE verifier of an authorization request for a few minutes, and are consumed once.
--
-- Users and bindings are part of the audited control-plane state (every change appends an
-- audit_log row in the same transaction). Session touches and pending logins are not.

CREATE TABLE app_user (
    id             TEXT PRIMARY KEY,
    issuer         TEXT NOT NULL,
    subject        TEXT NOT NULL,
    email          TEXT,
    name           TEXT,
    created_at     TIMESTAMPTZ NOT NULL,
    last_login_at  TIMESTAMPTZ,
    ord            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    UNIQUE (issuer, subject)
);

CREATE TABLE role_binding (
    id            TEXT PRIMARY KEY,
    subject_kind  TEXT NOT NULL CHECK (subject_kind IN ('user', 'group')),
    -- An app_user id for 'user', the group name as the IdP sends it for 'group'.
    subject       TEXT NOT NULL,
    role          TEXT NOT NULL
                  CHECK (role IN ('owner', 'admin', 'auditor', 'tenant_admin', 'developer', 'viewer', 'billing')),
    tenant_id     TEXT REFERENCES tenant (id),
    created_at    TIMESTAMPTZ NOT NULL,
    created_by    TEXT NOT NULL,
    ord           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    -- Deployment roles have no tenant; tenant roles always have one.
    CONSTRAINT role_binding_scope CHECK ((role IN ('owner', 'admin', 'auditor')) = (tenant_id IS NULL))
);
CREATE UNIQUE INDEX role_binding_unique ON role_binding (subject_kind, subject, role, coalesce(tenant_id, ''));

CREATE TABLE auth_session (
    id             TEXT PRIMARY KEY,
    -- Hex SHA-256 of the cookie token; the token itself is never stored.
    token_sha256   TEXT NOT NULL UNIQUE,
    user_id        TEXT NOT NULL REFERENCES app_user (id),
    -- The user's IdP groups at login (roles are recomputed from them on every request).
    groups         JSONB NOT NULL DEFAULT '[]',
    created_at     TIMESTAMPTZ NOT NULL,
    expires_at     TIMESTAMPTZ NOT NULL,
    last_seen_at   TIMESTAMPTZ NOT NULL,
    revoked_at     TIMESTAMPTZ
);
CREATE INDEX auth_session_user ON auth_session (user_id);
CREATE INDEX auth_session_expires ON auth_session (expires_at);

CREATE TABLE auth_login (
    state           TEXT PRIMARY KEY,
    -- Hex SHA-256 of the login cookie that binds the request to the browser that started it.
    binding_sha256  TEXT NOT NULL,
    nonce           TEXT NOT NULL,
    pkce_verifier   TEXT NOT NULL,
    return_to       TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    expires_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX auth_login_expires ON auth_login (expires_at);
