-- 0013: the durable node run journal (P3 M2). See crates/caliban-nodes/src/journal/ and
-- docs/nodes.md.
--
-- Never edit an applied migration; add a new one.
--
-- Absurd model: one schema, every step checkpointed as a row, workers claim runnable runs with
-- SELECT ... FOR UPDATE SKIP LOCKED and hold them under a lease they renew (heartbeat); a run whose
-- lease expired is taken over by another worker, which replays the recorded steps instead of
-- running them again. Durable sleeps and awaited events (human answers, timers) are rows too.
--
-- Payload columns (input, output, prompt, result, payload) hold values sealed under the tenant's
-- data key (base64 of nonce || ciphertext, tenant and run id as associated data). Deleting the
-- tenant destroys that key, which makes its runs unreadable (crypto-shredding). There is no
-- foreign key to tenant: workers write here, and a tenant's journal outlives nothing it can open.

CREATE TABLE node_run (
    id                    TEXT PRIMARY KEY,
    tenant_id             TEXT NOT NULL,
    node                  TEXT NOT NULL,
    version               INTEGER NOT NULL,
    spec_hash             TEXT NOT NULL,
    -- Who started the run ("api_key:<id or hash prefix>") and the key's hash, so the run's model
    -- calls are made, and limited, as that key; a revoked key stops its runs.
    invoker               TEXT NOT NULL,
    invoker_key_hash      TEXT,
    input                 TEXT NOT NULL,
    output                TEXT,
    status                TEXT NOT NULL CHECK (status IN ('pending', 'running', 'sleeping', 'input_required',
                                                          'succeeded', 'failed', 'budget_exhausted')),
    -- Runnable again at this time (durable sleep, human step timeout); NULL: now.
    wake_at               TIMESTAMPTZ,
    -- The event the run waits for (input_required) and the sealed question.
    awaiting              TEXT,
    prompt                TEXT,
    budget                JSONB NOT NULL,
    lease_owner           TEXT,
    lease_expires_at      TIMESTAMPTZ,
    claims                INTEGER NOT NULL DEFAULT 0,
    error                 TEXT,
    stop_reason           TEXT,
    idempotency_key       TEXT,
    idempotency_fingerprint TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    started_at            TIMESTAMPTZ,
    finished_at           TIMESTAMPTZ,
    CHECK ((status = 'running') = (lease_owner IS NOT NULL))
);
CREATE UNIQUE INDEX node_run_idempotency ON node_run (tenant_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX node_run_tenant ON node_run (tenant_id, created_at DESC);
-- What workers scan when they claim.
CREATE INDEX node_run_claimable ON node_run (created_at, id)
    WHERE status IN ('pending', 'sleeping', 'running', 'input_required');

-- One row per checkpointed step; (run_id, step_id) is written once (first write wins).
CREATE TABLE node_step (
    run_id       TEXT NOT NULL REFERENCES node_run(id) ON DELETE CASCADE,
    step_id      TEXT NOT NULL,
    tenant_id    TEXT NOT NULL,
    seq          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    attempt      INTEGER NOT NULL,
    vertex       TEXT NOT NULL,
    kind         TEXT NOT NULL,
    input_hash   TEXT NOT NULL,
    status       TEXT NOT NULL CHECK (status IN ('completed', 'failed')),
    result       TEXT,
    tokens       BIGINT NOT NULL DEFAULT 0,
    usd          DOUBLE PRECISION NOT NULL DEFAULT 0,
    started_at   TIMESTAMPTZ NOT NULL,
    finished_at  TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (run_id, step_id)
);

-- Awaited events: human answers (kind 'input', named after the human step) and timers (kind
-- 'timer', e.g. a human step's deadline). Written once.
CREATE TABLE node_event (
    run_id       TEXT NOT NULL REFERENCES node_run(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    tenant_id    TEXT NOT NULL,
    kind         TEXT NOT NULL CHECK (kind IN ('input', 'timer')),
    payload      TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (run_id, name)
);

DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['node_run', 'node_step', 'node_event']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format($p$CREATE POLICY tenant_isolation ON %I
                     USING (tenant_id = current_setting('app.tenant_id', true))$p$, t);
  END LOOP;
END $$;
