#!/usr/bin/env bash
# P0 measurement suite (reference architecture section 8): gateway overhead, tenant-isolation
# audit and usage accuracy. Builds release binaries, runs the overhead benchmark against the
# Rust mock upstream, runs the isolation and usage-accuracy integration tests, and writes a
# markdown report.
#
#   scripts/bench.sh                     # full run, report in bench/results/REPORT.md
#   QUICK=1 scripts/bench.sh             # fewer requests (smoke check of the suite itself)
#   CALIBAN_PII_NER_DIR=… scripts/bench.sh   # also build with `ner` and add the NER rows
#
# Knobs: BENCH_CONCURRENCY (default 1,16,64), BENCH_REQUESTS (4000), BENCH_WARMUP (400),
# BENCH_PACED_REQUESTS (600), BENCH_OUT (bench/results). Needs only cargo; no Docker, no Python.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=${BENCH_OUT:-bench/results}
mkdir -p "$OUT"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
TARGET=${CARGO_TARGET_DIR:-target}
REQUESTS=${BENCH_REQUESTS:-4000}; WARMUP=${BENCH_WARMUP:-400}; PACED=${BENCH_PACED_REQUESTS:-600}
if [[ -n "${QUICK:-}" ]]; then REQUESTS=400; WARMUP=50; PACED=60; fi

echo "== build (release)"
cargo build -q --release -p caliban -p caliban-bench
mkdir -p "$WORK/bin"
# Copy: a later `ner` build (or another checkout sharing the target dir) overwrites target/release.
cp "$TARGET/release/caliban" "$TARGET/release/mock-upstream" "$TARGET/release/caliban-bench" "$WORK/bin/"
NER_ARGS=()
if [[ -n "${CALIBAN_PII_NER_DIR:-}" ]]; then
  echo "== build (release, --features ner)"
  if cargo build -q --release -p caliban --features ner; then
    cp "$TARGET/release/caliban" "$WORK/bin/caliban-ner"
    NER_ARGS=(--caliban-ner "$WORK/bin/caliban-ner")
  else
    echo "   ner build failed; NER rows will be reported as skipped"
  fi
fi

COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
DIRTY=$(git status --porcelain 2>/dev/null | grep -q . && echo " (with uncommitted changes)" || true)
if [[ "$(uname)" == Darwin ]]; then
  CPU=$(sysctl -n machdep.cpu.brand_string)
  CORES="$(sysctl -n hw.ncpu) cores ($(sysctl -n hw.perflevel0.physicalcpu 2>/dev/null || echo ?) performance, $(sysctl -n hw.perflevel1.physicalcpu 2>/dev/null || echo ?) efficiency)"
  MEM="$(( $(sysctl -n hw.memsize) / 1073741824 )) GiB"
  OS="macOS $(sw_vers -productVersion)"
else
  CPU=$(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2- | xargs || uname -m)
  CORES="$(nproc) cores"
  MEM="$(awk '/MemTotal/ {printf "%d GiB", $2/1048576}' /proc/meminfo)"
  OS="$(uname -sr)"
fi
LOAD=$(uptime | sed 's/.*load averages*: //')

echo "== overhead benchmark"
"$WORK/bin/caliban-bench" --caliban "$WORK/bin/caliban" "${NER_ARGS[@]}" \
  --concurrency "${BENCH_CONCURRENCY:-1,16,64}" --requests "$REQUESTS" --warmup "$WARMUP" --paced-requests "$PACED" \
  --out "$OUT/overhead.md" --json "$OUT/overhead.json" \
  --note "Hardware: $CPU, $CORES, $MEM, $OS" \
  --note "Commit: \`$COMMIT\`$DIRTY; $(rustc -V)" \
  --note "Load average before the run: $LOAD" \
  --note "Date: $(date -u +%Y-%m-%dT%H:%MZ)"

echo "== isolation audit (cargo test -p caliban --test isolation)"
ISO_STATUS=pass
cargo test -p caliban --test isolation -- --test-threads=4 2>&1 | tee "$WORK/isolation.txt" || ISO_STATUS=fail

echo "== usage accuracy (cargo test -p caliban --test usage_accuracy)"
USAGE_STATUS=pass
USAGE_REPORT="$PWD/$OUT/usage.md" cargo test -p caliban --test usage_accuracy 2>&1 | tee "$WORK/usage.txt" || USAGE_STATUS=fail
# Known gaps are #[ignore]d tests: run them to record whether they still fail.
cargo test -p caliban --test usage_accuracy -- --ignored >"$WORK/gaps.txt" 2>&1 || true

{
  echo "# P0 measurement report"
  echo
  echo "Generated by \`scripts/bench.sh\`. Commit \`$COMMIT\`$DIRTY. $CPU, $OS."
  echo
  sed '1d' "$OUT/overhead.md"
  echo
  echo "## Isolation audit: $ISO_STATUS"
  echo
  grep -E '^test .* \.\.\. ' "$WORK/isolation.txt" | sed -E 's/^test (.*) \.\.\. (.*)$/- `\1`: \2/' || true
  echo
  echo "## Usage accuracy: $USAGE_STATUS"
  echo
  [[ -f "$OUT/usage.md" ]] && cat "$OUT/usage.md"
  echo
  echo "Known gaps (ignored tests; \"FAILED\" means the gap is still open):"
  echo
  grep -E '^test .* \.\.\. ' "$WORK/gaps.txt" | sed -E 's/^test (.*) \.\.\. (.*)$/- `\1`: \2/' || true
} > "$OUT/REPORT.md"
echo "wrote $OUT/REPORT.md"
[[ $ISO_STATUS == pass && $USAGE_STATUS == pass ]]
